feat(install): script now works when it clones itself

diff --git a/install b/install
--- a/install
+++ b/install
@@ -38,7 +38,7 @@ get_remote_url() {
     git -C "$1" config --get remote.origin.url
 }
 
-check_repo() {
+valid_repo() {
   remote_url=$(get_remote_url "$1")
   if [ "$remote_url" == "$GITHUB_DOWNLOAD" ]; then
       return 0
@@ -69,22 +69,28 @@ log_crit() {
 }
 
 parse_args() {
-	while getopts "i:l:fh" arg; do
-		case "${arg}" in
-		i) INSTALL_DIR="${OPTARG}" ;;
-                l)
-                   case ${OPTARG} in
-                     ''|*[!0-9]*) echo "Error: -l requires an integer argument" ; exit 1 ;;
-                     *) LOG_LEVEL=${OPTARG} ;;
-                   esac
-                   ;;
-                f) FORCE=1 ;;
-		h | \?) usage "$0" ;;
-		*) return 1 ;;
-		esac
-	done
-	shift $((OPTIND - 1))
-	EXECARGS="$*"
+	while getopts "i:l:fh" arg; do case "$arg" in
+		i) INSTALL_DIR="${OPTARG}";;
+		l) [ "$OPTARG" -ge 0 -a "$OPTARG" -le 2 ] 2>/dev/null && LOG_LEVEL="$OPTARG" || { echo "Error: -l requires an integer argument"; exit 1; };;
+		f) FORCE=1;;
+		*) usage "$0";;
+	esac; done
+}
+
+install_dotfiles() {
+  if ! mkdir "${INSTALL_DIR}" &>/dev/null && ! valid_repo "${INSTALL_DIR}"; then
+    [ -d "${INSTALL_DIR}" ] && mv -n "${INSTALL_DIR}" "${INSTALL_DIR}-backup" && log_crit "Directory ${INSTALL_DIR} is moved for backup."
+    log_info "Cloning dotfiles repo from ${GITHUB_DOWNLOAD}"
+    git clone --recurse-submodules ${GITHUB_DOWNLOAD} ${INSTALL_DIR}
+    return 1
+  fi
+
+  git -C "${INSTALL_DIR}" fetch --quiet
+  LOCAL_COMMIT=$(git -C "${INSTALL_DIR}" rev-parse HEAD)
+  REMOTE_COMMIT=$(git -C "${INSTALL_DIR}" rev-parse @{u})
+
+  [ "$LOCAL_COMMIT" != "$REMOTE_COMMIT" ] || [ "$FORCE" -ne 0 ] && log_info "Pulling remote changes" && git -C "${INSTALL_DIR}" pull && return 1
+  return 0
 }
 
 dotbot() {
@@ -105,31 +111,9 @@ main() {
     exit 1
   fi
 
-  if ! mkdir "${INSTALL_DIR}" &>/dev/null; then
-    log_info "Directory ${INSTALL_DIR} exists. Checking if proper dotfiles repo."
-    if ! check_repo "${INSTALL_DIR}" ; then
-      log_crit "Directory ${INSTALL_DIR} exists and is not a proper dotfiles repo. Moving."
-      mv -n "${INSTALL_DIR}" "${INSTALL_DIR}-backup"
-      log_info "Cloning dotfiles repo from ${GITHUB_DOWNLOAD}"
-      git clone --recurse-submodules ${GITHUB_DOWNLOAD} ${INSTALL_DIR}
-      # TODO: can return here
-    fi
-
-    git -C "${INSTALL_DIR}" fetch --quiet
-
-    LOCAL_COMMIT=$(git -C "${INSTALL_DIR}" rev-parse HEAD)
-    REMOTE_COMMIT=$(git -C "${INSTALL_DIR}" rev-parse @{u})  # @{u} shorthand for the upstream branch
-
-    if [ "$LOCAL_COMMIT" = "$REMOTE_COMMIT" ] && [ "$FORCE" -eq 0 ]; then
+  if install_dotfiles ; then
       log_info "Proper dotfiles repo exists and up-to-date. Goodbye."
       exit 0
-    else
-      log_info "Pulling remote changes"
-      git -C "${INSTALL_DIR}" pull
-    fi
-  else
-    log_info "Cloning dotfiles repo from ${GITHUB_DOWNLOAD}"
-    git clone --recurse-submodules ${GITHUB_DOWNLOAD} ${INSTALL_DIR}
   fi
 
   dotbot || (log_crit "Installation failed" && exit 1)
